import {describe,it,expect} from 'vitest';
import {createNode,duplicateNodes,graphProblems,searchNodes} from './editor';
import {exampleGraph} from './model';
import {GraphHistory} from './useGraphHistory';
describe('graph editing contracts',()=>{
 it('searches full names and abbreviations without fixed outputs',()=>{expect(searchNodes(' exponential moving ')).toEqual(['ema']);expect(searchNodes('rSi')).toEqual(['rsi']);expect(searchNodes('Entry Long')).toEqual([]);expect(searchNodes('')).toHaveLength(14);});
 it('creates independent defaults and remaps only internal duplicate edges',()=>{const a=createNode('ema'),b=createNode('ema');a.params.period=3;expect(b.params.period).toBe(20);expect(a.id).not.toBe(b.id);const graph=exampleGraph();const copy=duplicateNodes(graph,{close:{x:10,y:20}},['close','mean','out:entry_long']);expect(copy.selected).toHaveLength(2);expect(copy.graph.nodes[5].inputs.source).toBe(copy.selected[0]+'.value');expect(copy.graph.outputs).toEqual(graph.outputs);expect(graph.nodes).toHaveLength(4);expect(copy.layout[copy.selected[0]]).toEqual({x:50,y:60});});
 it('groups an entire drag, bounds undo and invalidates redo after editing',()=>{const h=new GraphHistory({graph:exampleGraph(),layout:{}},2);h.begin();for(let x=1;x<=10;x++)h.change({graph:h.current.graph,layout:{close:{x,y:0}}});h.end();expect(h.past).toHaveLength(1);h.undo();expect(h.current.layout).toEqual({});h.redo();expect(h.current.layout.close.x).toBe(10);h.undo();h.change({graph:h.current.graph,layout:{close:{x:22,y:0}}});expect(h.future).toHaveLength(0);h.change({graph:h.current.graph,layout:{}});h.change({graph:h.current.graph,layout:{close:{x:1,y:1}}});expect(h.past).toHaveLength(2);h.reset({graph:exampleGraph(),layout:{}});expect(h.past).toHaveLength(0);});
 it('locates disconnected inputs and invalid parameters without changing drafts',()=>{const g=exampleGraph();g.nodes[1].inputs.source='';g.nodes[1].params.period=0;const problems=graphProblems(g);expect(problems).toEqual(expect.arrayContaining([expect.objectContaining({node:'mean',field:'source'}),expect.objectContaining({node:'mean',field:'period'})]));expect(g.nodes[1].inputs.source).toBe('');});
});
