import {useEffect,useState} from 'react';
import {api} from './api';
import {poll} from './poll';
import type {Profile} from './model';
import LiveChart from './LiveChart';
import {OrderBookPanel,TradeTape} from './MarketPanels';

const when=(seconds:number)=>new Date(seconds*1000).toISOString().replace('T',' ').slice(0,19)+' UTC';
const show=(value:any)=>value==null||value===''?'—':String(value);
const panels=['Position','Strategy','Signals','Paper Trades','Notifications','Log'];
export default function LiveTerminal({strategyId,profile,onProfileChange}:{strategyId:string|null;profile:Profile;onProfileChange?:(p:Profile)=>void}){
 const [status,setStatus]=useState<any>({}),[paper,setPaper]=useState(false),[channels,setChannels]=useState<string[]>([]),[source,setSource]=useState('strategy');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[panel,setPanel]=useState('Position'),[busy,setBusy]=useState(false),[transportFailed,setTransportFailed]=useState(false);
 const [token,setToken]=useState(''),[chat,setChat]=useState(''),[configure,setConfigure]=useState(false);
 useEffect(()=>poll(()=>api<any>('live_status'),s=>{setStatus(s);setTransportFailed(false);},()=>{setTransportFailed(true);setError('Live service is unavailable; displayed values are stale.');},500),[]);
 useEffect(()=>{if(status.session&&status.options){setPaper(status.options.paper);setChannels(status.options.channels);setSource(status.options.execution_source??'strategy');}},[status.session?.id]);
 async function act(command:string,params:Record<string,unknown>={}){
  setBusy(true);setError('');try{
   const result=await api<any>(command,params);
   if(command==='live_replay')setNotice(result.match?`MATCH — ${result.checked_events} recorded signal events`:'MISMATCH — inspect session before continuation');
   if(command==='notification_test')setNotice('Test queued. Delivery outcome appears below and in Log.');
   if(command==='telegram_configure'){setToken('');setChat('');setConfigure(false);}
   if(command==='paper_manual')setNotice(`PAPER request ${result.status}; execution waits for the next valid observed quote.`);
   setStatus(await api<any>('live_status'));
  }catch(e){setError(String(e));}finally{setBusy(false);}
 }
 const session=status.session,activeProfile=status.active?(session?.snapshot.profile??profile):profile,market=status.market??{},ticker=market.ticker??{},account=status.paper,position=account?.position;
 useEffect(()=>{let gone=false;api('market_open',{market:activeProfile.market,symbol:activeProfile.symbol}).catch(e=>{if(!gone)setError(String(e));});return()=>{gone=true;};},[activeProfile.market,activeProfile.symbol]);
 useEffect(()=>()=>{api('market_close').catch(()=>{});},[]);
 const connected=(market.active??status.active)&&status.terminal_state==='CONNECTED'&&!transportFailed;
 const fresh=connected&&market.fresh,signals=status.evaluation?.signals??{};
 const manual=connected&&status.active&&session?.status==='CONNECTED'&&!busy&&!status.paper_paused&&!account?.pending_observations&&status.options?.paper&&status.options?.execution_source==='manual';
 const action=(action:string)=>act('paper_manual',{session_id:session.id,action,request_id:crypto.randomUUID().replaceAll('-','')});
 const update=(key:string,value:any)=>onProfileChange?.({...profile,[key]:value});
 const notificationLog=(status.log??[]).filter((r:any)=>/notification|delivery|Telegram/i.test(r.message)).slice(-10);
 return <section className="live-terminal" aria-label="Live Terminal">
  <div className="market-header"><div><strong>{activeProfile.symbol}</strong><small>{activeProfile.market} · No real orders</small></div><div className={!fresh?'stale':''}><b>{show(ticker.lastPrice??status.price)}</b><small>Last {fresh?'':'· stale / waiting'}</small></div>
   {[['Mark',ticker.markPrice],['24h change',ticker.price24hPcnt!=null?`${(Number(ticker.price24hPcnt)*100).toFixed(2)}%`:null],['24h high',ticker.highPrice24h],['24h low',ticker.lowPrice24h],['24h volume',ticker.volume24h],['Funding',ticker.fundingRate!=null?`${(Number(ticker.fundingRate)*100).toFixed(6)}%`:null]].map(([label,value])=><div className={!fresh?'stale':''} key={label}><span>{show(value)}</span><small>{label}</small></div>)}
   <strong className={connected?'positive':'warning'} role="status">● {transportFailed?'DEGRADED':status.terminal_state??session?.status??'PAUSED'}</strong></div>
  <div className="terminal-controls"><strong>{session?.snapshot.strategy_name??(strategyId?'Selected saved strategy':'Strategy: NOT SELECTED')}</strong><span>Strategy timeframe: {activeProfile.primary_minutes}m / {activeProfile.evaluation}</span><span>Evaluation: {status.evaluation?when(status.evaluation.time):'waiting'}</span><span>Strategy: {status.strategy_state??'NOT SELECTED'}</span>{status.active&&status.strategy_state==='WARMING UP'&&status.warmup&&<span role="status">Preparing history: {status.warmup.recovered.toLocaleString()} / {status.warmup.required.toLocaleString()} M1</span>}
   <button disabled={!strategyId||status.active||busy} onClick={()=>act('live_start_terminal',{strategy_id:strategyId,profile,paper,channels,execution_source:source})}>Start new live session</button><button disabled={!status.active||busy} onClick={()=>act('live_pause')}>Pause</button>{session&&<button disabled={status.active||busy} onClick={()=>act('live_resume',{session_id:session.id,revalidate_paper:false})}>Recover monitoring</button>}
   <details className="live-settings"><summary>Live settings</summary><div><p>New sessions freeze these settings. Display timeframe never changes them.</p><label><input type="checkbox" checked={paper} disabled={status.active} onChange={e=>setPaper(e.target.checked)}/> Paper trading</label><label>Paper execution source<select aria-label="Paper execution source" value={source} disabled={status.active} onChange={e=>setSource(e.target.value)}><option value="strategy">Strategy</option><option value="manual">Manual</option></select></label>
    <label>Market<select value={profile.market} disabled={status.active} onChange={e=>onProfileChange?.({...profile,market:e.target.value,leverage:e.target.value==='spot'?'1':profile.leverage})}><option value="spot">spot</option><option value="linear">linear</option></select></label><label>Instrument<input value={profile.symbol} disabled={status.active} onChange={e=>update('symbol',e.target.value)}/></label>
    <label>Strategy timeframe<select value={profile.primary_minutes} disabled={status.active} onChange={e=>update('primary_minutes',Number(e.target.value))}>{[1,3,5,15,30,60,120,240,360,720,1440].map(n=><option key={n} value={n}>{n}m</option>)}</select></label><label>Evaluation mode<select value={profile.evaluation} disabled={status.active} onChange={e=>update('evaluation',e.target.value)}><option value="closed">closed</option><option value="intrabar">forming</option></select></label>
    {['capital','allocation','leverage','fee_rate','slippage','stop_loss','take_profit'].map(key=><label key={key}>{key.replaceAll('_',' ')}<input disabled={status.active} value={profile[key]} onChange={e=>update(key,e.target.value)}/></label>)}<small>Rates are fractions (0.01 = 1%). Full modeling settings remain available in Backtest.</small></div></details>
   {!!status.sessions?.length&&<select aria-label="Saved live session" disabled={status.active||busy} value={session?.id??''} onChange={e=>act('live_select',{session_id:e.target.value})}>{status.sessions.map((s:any)=><option key={s.id} value={s.id}>{s.name} · {s.status}</option>)}</select>}
  </div>
  {(error||notice)&&<div className="terminal-message"><span role={error?'alert':'status'}>{error||notice}</span><button aria-label="Dismiss message" onClick={()=>{setError('');setNotice('');}}>×</button></div>}
  <div className="terminal-market"><LiveChart sessionId={session?.snapshot.profile.symbol===activeProfile.symbol&&session?.snapshot.profile.market===activeProfile.market?session?.id:undefined} market={activeProfile.market} symbol={activeProfile.symbol} paper={account} price={ticker.lastPrice} mark={ticker.markPrice} fresh={!!fresh}/><aside className="market-side"><OrderBookPanel book={market.book} age={market.book_age} active={!!(market.active??status.active)&&!transportFailed}/><TradeTape trades={market.trades??[]} active={!!(market.active??status.active)&&!transportFailed}/></aside></div>
  <div className="terminal-bottom"><nav aria-label="Live panels">{panels.map(name=><button key={name} className={panel===name?'active':''} onClick={()=>setPanel(name)}>{name}</button>)}</nav><div className="terminal-panel" role="region" aria-label={panel}>
   {panel==='Position'&&<><div className="paper-heading"><strong className="paper-badge">PAPER · {status.options?.execution_source??source}</strong><span>{activeProfile.symbol} · {position?`${position.side} ${position.quantity} @ ${position.entry}`:'No position'}</span><button disabled={!manual||!!position} onClick={()=>action('buy')}>Paper Buy</button><button disabled={!manual||!!position||activeProfile.market==='spot'} onClick={()=>action('sell')}>Paper Sell</button><button disabled={!manual||!position} onClick={()=>action('close')}>Close Paper Position</button></div><div className="paper-stats">{[['Cash',account?.cash],['Equity',account?.equity],['Unrealized PnL',account?.unrealized_pnl],['Realized net PnL',account?.realized_net_pnl],['Session PnL',account?.net_pnl],['Last / mark',`${show(account?.current_price)} / ${show(account?.mark)}`],['Stop',position?.stop],['Take',position?.take],['Fees',account?.fees],['Funding',account?.funding]].map(([name,value])=><div key={name}><small>{name}</small><strong>{show(value)}</strong></div>)}</div>
    {status.paper_paused&&session&&<p className="warning">Missing ticks are not recovered. Review the PAPER position before continuation. <button disabled={busy} onClick={()=>act('live_resume',{session_id:session.id,revalidate_paper:true})}>Revalidate paper continuity and resume</button></p>}{account?.waiting_funding&&<p>Waiting for confirmed funding; {account.pending_observations} recorded observations pending.</p>}<small>Virtual observed-price execution, configured fees/slippage, no exchange fill guarantee. Manual source disables strategy orders, not strategy signals or protections.</small>{status.manual_requests?.map((r:any)=><span className="manual-request" key={r.id}>PAPER {r.action}: {r.status}</span>)}</>}
   {panel==='Strategy'&&<><p>Live: {status.active?'Running':'Paused'} · {session?.detail} · Last valid minute: {session?.last_minute!=null?when(session.last_minute+60):'None'}</p><div className="strategy-signals">{['entry_long','exit_long','entry_short','exit_short'].map(key=><div key={key}><small>{key.replaceAll('_',' ')}</small><strong>{status.evaluation?(signals[key]?'TRUE':'FALSE'):'Awaiting evaluation'}</strong></div>)}</div><div className="indicator-values">{Object.entries(status.evaluation?.values??{}).map(([name,value])=><span key={name}>{name}: <b>{show(value)}</b></span>)}</div><small>Values are produced by Strategy IR at confirmed M1 boundaries, including forming higher-timeframe evaluation.</small></>}
   {panel==='Signals'&&<>{session&&<button disabled={busy||status.active} onClick={()=>act('live_replay',{session_id:session.id})}>Verify recorded signals with replay</button>}<table><thead><tr><th>Signal time</th><th>Transition</th><th>Price</th><th>Source / delivery</th><th>IR snapshot</th></tr></thead><tbody>{status.events?.slice(0,100).map((e:any)=><tr key={e.id}><td>{when(e.time)}</td><td>{e.type.replaceAll('_',' ')}</td><td>{show(e.price)}</td><td>{e.source} / {e.delivery}</td><td>{Object.entries(e.values??{}).map(([k,v])=>`${k}: ${show(v)}`).join(' · ')}</td></tr>)}</tbody></table></>}
   {panel==='Paper Trades'&&<table><thead><tr><th>Observed time</th><th>Side / reason</th><th>Quantity</th><th>Fill</th><th>Fee</th></tr></thead><tbody>{status.paper_history?.slice(0,50).flatMap((r:any,i:number)=>r.fills.map((f:any,j:number)=><tr key={`${i}-${j}`}><td>{when(r.time_ns/1e9)}</td><td>PAPER {f.side} / {f.reason}</td><td>{f.quantity}</td><td>{f.price}</td><td>{f.fee}</td></tr>))}</tbody></table>}
   {panel==='Notifications'&&<><div className="notification-controls">{['windows','sound','telegram'].map(channel=><div key={channel}><label><input type="checkbox" checked={channels.includes(channel)} disabled={status.active} onChange={e=>setChannels(xs=>e.target.checked?[...xs,channel]:xs.filter(x=>x!==channel))}/>{channel==='windows'?'Windows':channel==='sound'?'Sound':'Telegram'}</label><button disabled={busy} onClick={()=>act('notification_test',{channel})}>Test {channel}</button></div>)}<span>Telegram: {status.telegram?.configured?'Configured in Windows Credential Manager':'Not configured'}</span><button onClick={()=>{setConfigure(v=>!v);setToken('');setChat('');}}>Configure Telegram</button><button disabled={busy||!status.telegram?.configured} onClick={()=>act('telegram_clear')}>Clear stored credentials</button></div>
    {configure&&<form className="telegram-form" autoComplete="off" onSubmit={e=>{e.preventDefault();act('telegram_configure',{token,chat_id:chat});}}><label>Bot token<input type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)}/></label><label>Chat ID<input type="password" autoComplete="off" value={chat} onChange={e=>setChat(e.target.value)}/></label><button disabled={busy}>Save to protected storage</button></form>}{notificationLog.map((r:any,i:number)=><p key={i}>{r.message}</p>)}<small>Telegram delivery remains subject to real owner acceptance (ILI-37). Channel failure never stops strategy evaluation.</small></>}
   {panel==='Log'&&<><details><summary>Market stream counters</summary><div className="indicator-values">{Object.entries(market.counts??{}).map(([name,value])=><span key={name}>{name}: {show(value)}</span>)}</div><small>Connections count successful subscription sets. Tape resets on reconnect; it is not historical storage.</small></details><ol className="terminal-log">{status.log?.slice(-200).reverse().map((e:any,i:number)=><li key={`${e.time}-${i}`}><time>{when(e.time/1000)}</time> {e.message}</li>)}</ol></>}
  </div></div>
 </section>;
}
