import type {PositionConfiguration,Profile} from './model';

export function positionDefaults(profile:Profile):PositionConfiguration{return {version:1,repeated_entry:'ignore',scale_allocation_percent:'10',max_entries:1,max_allocation_percent:'100',max_position_notional:String(profile.max_notional),max_leverage:String(profile.leverage),dca:[],partial_take:[],trailing_activation:'0',trailing_distance:'0',break_even_activation:'0',atr_period:14,atr_stop_multiplier:'0',atr_trailing_multiplier:'0'};}

export default function PositionSettings({profile,onChange,disabled=false}:{profile:Profile;onChange:(profile:Profile)=>void;disabled?:boolean}){
 const config=profile.position_management;
 const change=(patch:Partial<PositionConfiguration>)=>onChange({...profile,version:2,position_management:{...config!,...patch}});
 const field=(key:keyof PositionConfiguration,label:string,percent=false,integer=false)=><label className="field"><span>{label}</span><input aria-label={label} type="number" step={integer?'1':'any'} value={percent?Number(config![key])*100:String(config![key])} onChange={e=>change({[key]:integer?Number(e.target.value):percent?String(Number(e.target.value)/100):e.target.value})}/></label>;
 return <details className="position-settings"><summary>Position Management</summary><fieldset disabled={disabled}>
  <label><input type="checkbox" aria-label="Enable Position Management" checked={!!config} onChange={e=>{const next={...profile};if(e.target.checked){next.position_management=positionDefaults(profile);next.version=2;}else delete next.position_management;onChange(next);}}/> Enable Position Management</label>
  <small>Optional shared Backtest/Paper policy. Disabled preserves legacy behavior. Rates below are percentages; no real orders.</small>
  {config&&<><details open><summary>Scaling and limits</summary><label className="field"><span>Repeated entry</span><select aria-label="Repeated entry" value={config.repeated_entry} onChange={e=>change({repeated_entry:e.target.value})}><option value="ignore">Ignore</option><option value="scale">Scale on a new signal transition</option></select></label>
   {field('scale_allocation_percent','Add allocation (% of initial capital)')}{field('max_entries','Maximum entries',false,true)}{field('max_allocation_percent','Maximum allocated capital (%)')}{field('max_position_notional','Maximum position notional (USDT)')}{field('max_leverage','Maximum leverage')}
   <small>Entries include the first entry. Limits reject additions without silently resizing them.</small></details>
   <details><summary>DCA steps ({config.dca.length}/8)</summary><small>Adverse distance from the first entry; one attempt per step.</small>{config.dca.map((row,i)=><div className="position-step" key={i}><label>Distance (%)<input aria-label={`DCA ${i+1} distance (%)`} type="number" step="any" value={Number(row.distance)*100} onChange={e=>change({dca:config.dca.map((r,j)=>j===i?{...r,distance:String(Number(e.target.value)/100)}:r)})}/></label><label>Capital (%)<input aria-label={`DCA ${i+1} allocation (%)`} type="number" step="any" value={row.allocation_percent} onChange={e=>change({dca:config.dca.map((r,j)=>j===i?{...r,allocation_percent:e.target.value}:r)})}/></label><button onClick={()=>change({dca:config.dca.filter((_,j)=>j!==i)})}>Remove DCA {i+1}</button></div>)}<button disabled={config.dca.length>=8} onClick={()=>change({dca:[...config.dca,{distance:String(Number(config.dca.at(-1)?.distance??0)+.02),allocation_percent:'10'}]})}>Add DCA step</button></details>
   <details><summary>Partial take profit ({config.partial_take.length}/8)</summary><small>Fractions use quantity at the first take trigger; a cumulative 100% closes all remaining quantity.</small>{config.partial_take.map((row,i)=><div className="position-step" key={i}><label>Profit distance (%)<input aria-label={`Take ${i+1} distance (%)`} type="number" step="any" value={Number(row.distance)*100} onChange={e=>change({partial_take:config.partial_take.map((r,j)=>j===i?{...r,distance:String(Number(e.target.value)/100)}:r)})}/></label><label>Reduce (%)<input aria-label={`Take ${i+1} reduction (%)`} type="number" step="any" value={Number(row.fraction)*100} onChange={e=>change({partial_take:config.partial_take.map((r,j)=>j===i?{...r,fraction:String(Number(e.target.value)/100)}:r)})}/></label><button onClick={()=>change({partial_take:config.partial_take.filter((_,j)=>j!==i)})}>Remove take {i+1}</button></div>)}<button disabled={config.partial_take.length>=8} onClick={()=>change({partial_take:[...config.partial_take,{distance:String(Number(config.partial_take.at(-1)?.distance??0)+.03),fraction:'.25'}]})}>Add partial take</button></details>
   <details><summary>Trailing, break-even and ATR</summary>{field('trailing_activation','Trailing activation (%)',true)}{field('trailing_distance','Trailing distance (%)',true)}{field('break_even_activation','Break-even activation (%)',true)}{field('atr_period','ATR period (confirmed primary bars)',false,true)}{field('atr_stop_multiplier','ATR stop multiplier')}{field('atr_trailing_multiplier','ATR trailing multiplier')}<small>Zero disables the corresponding protection. Stops never loosen. Break-even includes remaining costs and configured exit slippage; gap fills can still lose money.</small></details>
  </>}
 </fieldset></details>;
}
